www/internal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from internal import views

urlpatterns = [
  url(r'^chain/$', views.chain, name='chain'),
  url(r'^network/$', views.network, name='network'),
  url(r'^add_node/$', views.add_node, name='add_node'),
  url(r'^remove_node/$', views.remove_node, name='remove_node'),
  url(r'^approve_peer_request/$', views.approve_peer_request, name='approve_peer_request'),
  url(r'^request_peer/$', views.request_peer, name='request_peer'),
  url(r'^end_peering/$', views.end_peering, name='end_peering'),
  url(r'^certify/$', views.certify, name='certify'),
  url(r'^manage_certifications/$', views.manage_certifications, name='manage_certifications'),
  url(r'^queue_certifications/$', views.queue_certifications, name='queue_certifications'),
  url(r'^revoke_document/$', views.revoke_document, name='revoke_document'),
  url(r'^discard_pending_block/$', views.discard_pending_block, name='discard_pending_block'),
  url(r'^submit_pending_block/$', views.submit_pending_block, name='submit_pending_block'),
  url(r'^user_options/$', views.user_options, name='user_options'),
]

www/www/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from public.views import index as index_view

urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^$', auth_views.login),
    #url(r'^logout/', auth_views.logout),
    url(r'^$', index_view),
    url(r'^internal/', include('internal.urls', namespace='internal')),
    url(r'^public/', include('public.urls', namespace='public')),
]

www/internal/models.py
from django.db import models

www/internal/views.py
from __future__ import division
import requests, json, base64
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.conf import settings
from internal.shared import create_rpc_url
from django import forms
import os, hashlib, csv

#@login_required
def chain(request):
  try:
    pending_blocks_resp = requests.get(create_rpc_url('/pending_blocks'))
    hashchain_resp = requests.get(create_rpc_url('/hashchain'))
    return render(request, 'internal/chain.html', {
      'pending_blocks' : pending_blocks_resp.json(),
      'processing_block': hashchain_resp.json()[0],
      'latest_n_hcblocks': hashchain_resp.json()[1]
    })
  except Exception as ex:
    messages.error(request, 'Your institution\'s CertChain node \
      is not available at this time.')
    return render(request, 'internal/chain.html', {})

#@login_required
def network(request):
  try:
    resp = requests.get(create_rpc_url('/network'))
    return render(request, 'internal/network.html',\
      {'network' : resp.json()})
  except Exception as ex:
    messages.error(request, 'Your institution\'s CertChain node \
      is not available at this time.')
    return render(request, 'internal/network.html', {})

#@login_required
def add_node(request):
  if request.method == 'POST':
    payload = {
      'hostname': request.POST['hostname'],
      'port': request.POST['port'],
      'address': request.POST['address']
    }
    resp = requests.post(create_rpc_url('/add_node'),
      data=json.dumps(payload))
    if resp.status_code == 200 and resp.text == 'OK':
      messages.success(request,\
        'The node was added to the list of known nodes.')
    else:
      messages.error(request,\
        'An error occurred while adding the node you specified: '
        + str(resp.text))
    return redirect(reverse('internal:overview'))
  raise Http404

#@login_required
def remove_node(request):
  if request.method == 'POST':
    inst_addr = request.POST['inst_addr']
    resp = requests.post(create_rpc_url('/remove_node/' + inst_addr))
    if resp.status_code == 200 and resp.text == 'OK':
      messages.success(request,\
        'The node was removed from the list of known nodes.')
    else:
      messages.error(request,\
        'An error occurred while removing the node you specified: '
        + str(resp.text))
    return redirect(reverse('internal:overview'))
  raise Http404

#@login_required
def approve_peer_request(request):
  if request.method == 'POST':
    addr = request.POST['requesting_addr']
    resp = requests.post(create_rpc_url('/approve_peerreq/' + addr))
    if resp.status_code == 200 and resp.text == 'OK':
      messages.success(request,\
        'Your approval was submitted successfully.')
    else:
      messages.error(request,\
        'An error occurred while processing your \
        peer request approval: ' + resp.text)
    return redirect(reverse('internal:overview'))
  raise Http404

#@login_required
def request_peer(request):
  if request.method == 'POST':
    addr = request.POST['addr']
    resp = requests.post(create_rpc_url('/request_peer/' + addr))
    if resp.status_code == 200 and resp.text == 'OK':
      messages.success(request,\
        'Your peering request was successfully submitted.')
    else:
      messages.error(request,\
        'An error occurred while processing your \
        peer request: ' + resp.text)
    return redirect(reverse('internal:overview'))
  raise Http404

#@login_required
def end_peering(request):
  if request.method == 'POST':
    addr = request.POST['addr']
    resp = requests.post(create_rpc_url('/end_peering/' + addr))
    if resp.status_code == 200 and resp.text == 'OK':
      messages.success(request,\
        'Your peering termination request was successfully submitted.')
    else:
      messages.error(request,\
        'An error occurred while processing your \
        peering termination request: ' + resp.text)
    return redirect(reverse('internal:overview'))
  raise Http404

#@login_required
def certify(request):
  return render(request, 'internal/certify.html', {})

#@login_required
def manage_certifications(request):
  try:
    resp = requests.get(create_rpc_url('/all_certifications'))
    return render(request, 'internal/certifications.html',\
      {'certifications' : resp.json()})
  except Exception as ex:
    messages.error(request, 'Your institution\'s CertChain node \
      is not available at this time.')
    return render(request, 'internal/certifications.html', {})

#@login_required
def queue_certifications(request):
  if request.method == 'POST':
    payload = request.POST['certify_payload']
    resp = requests.post(create_rpc_url('/certify'),
      data=payload)
    if resp.status_code == 200 and resp.text == 'OK':
      messages.success(request,\
        'The certifications have been submitted successfully as a new pending block.')
      return redirect(reverse('internal:chain'))
    else:
      messages.error(request,\
        'An error occurred while processing your \
        certification request: ' + resp.text)
      return redirect(reverse('internal:certify'))
  raise Http404

#@login_required
def revoke_document(request):
  if request.method == 'POST':
    docid = request.POST['docid_to_revoke']
    resp = requests.post(create_rpc_url('/revoke/' + docid))
    if resp.status_code == 200:
      messages.success(request,\
        'Your document revocation request has been submitted as a new pending block.')
      return redirect(reverse('internal:chain'))
    else:
      messages.error(request,\
        'An error occurred while processing your revocation \
        request: ' + str(resp.status_code))
    return redirect(reverse('internal:manage_certifications'))
  raise Http404

#@login_required
def discard_pending_block(request):
  if request.method == 'POST':
    discard_id = request.POST['discard_id']
    resp = requests.post(create_rpc_url('/discard_pending_block/' + discard_id))
    if resp.status_code == 200:
      messages.success(request,\
        'The pending block was successfully discarded.')
    else:
      messages.error(request,\
        'An error occurred while processing your discard \
        request: ' + str(resp.status_code))
    return redirect(reverse('internal:chain'))
  raise Http404

#@login_required
def submit_pending_block(request):
  if request.method == 'POST':
    submit_id = request.POST['submit_id']
    resp = requests.post(create_rpc_url('/submit_pending_block/' + submit_id))
    if resp.status_code == 200:
      messages.success(request,\
        'The pending block was successfully submitted.')
    else:
      messages.error(request,\
        'An error occurred while processing your submission \
        request: ' + str(resp.status_code))
    return redirect(reverse('internal:chain'))
  raise Http404

#@login_required
def user_options(request):
  return render(request, 'internal/user_options.html', {})

www/internal/templates/includes/menu.html
<div class="row">
  <div id="cc-secure-links" class="span12">
    <span><a href="{% url 'internal:chain' %}">Chain Status</a></span>
    <span>-</span>
    <span><a href="{% url 'internal:certify' %}">Certify Documents</a></span>
    <span>-</span>
    <span><a href="{% url 'internal:manage_certifications' %}">Manage Certifications</a></span>
    <span>-</span>
    <span><a href="{% url 'internal:network' %}">Network Peers</a></span>
  </div>
</div>

www/internal/templates/internal/auth_base.html
{% extends "base.html" %}

{% block authbar %}
<span class="cc-bar-entry">
  <a href="{% url 'internal:user_options' %}">{{ request.session.FULL_NAME }}</a>
</span>
<a class="cc-btn" href="/logout">LOGOUT</a>
{% endblock authbar %}

www/internal/templates/internal/certifications.html
{% extends "internal/auth_base.html" %}

{% load certchain_extras %}

{% block content %}
<div class="container cc-container">
  {% include "includes/menu.html" %}

  <div class="row">
    <div class="span12">
      <h2>Manage Certifications</h2>
      <p>The list below reflects the current state of all documents certified by your institution on the CertChain network. Documents are ordered from most to least recent.</p>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <table id="cc-diploma-table" class="table">
        <tr>
          <th>Issued To</th>
          <th>Document ID</th>
          <th style="text-align: center">Certfied</th>
          <th style="text-align: center">Revoked</th>
        </tr>
        {% for c in certifications %}
        <tr>
          <td>{{ c.user_id }}</td>
          <td>{{ c.doc_id }}</td>
          <td style="text-align: center">{{ c.cert_timestamp | cc_unix_epoch_to_date }}</td>
          <td style="text-align: center">
            {% if c.rev_timestamp %}
              <span>{{ c.rev_timestamp | cc_unix_epoch_to_date }}</span>
            {% else %}
            <form method="post" action="{% url 'internal:revoke_document' %}">
              {% csrf_token %}
              <input name="docid_to_revoke" type="hidden" value="{{ c.doc_id }}"/>
              <input class="cc-btn" type="submit" value="REVOKE"/>
            </form>
            {% endif %}
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="7">Your institution has not issued any certifications yet.</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
{% endblock content %}

www/internal/templates/internal/certify.html
{% extends "internal/auth_base.html" %}

{% load certchain_extras %}
{% load staticfiles %}

{% block stylesheets %}
  {{ block.super }}
  <link href="{% static 'internal/css/certify.css'%}" rel="stylesheet"/>
{% endblock stylesheets %}

{% block javascript %}
  {{ block.super }}
  <script type='text/javascript' src="{% static 'public/js/knockout-3.4.1.js'%}"></script>
  <script type="text/javascript" src="{% static 'internal/js/jquery-1.10.2.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'public/js/sjcl.js'%}"></script>
  <script type="text/javascript" src="{% static 'public/js/forge.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'public/js/progressbar.js'%}"></script>
  <script type="text/javascript" src="{% static 'internal/js/certify.js'%}"></script>
{% endblock javascript %}

{% block content %}

<div class="container cc-container">
  {% include "includes/menu.html" %}

  <div class="row">
    <div class="span12">
      <h2>Certify from CSV Manifest</h2>
      <p>Upload a CSV manifest file listing each document to be certified.</p>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <div class="certify-area">
        <div id="csv-file-selector" data-bind="visible: csvToSendCertChain() == null">
          <input type="file" id="csv_file_upload" name="csvfile" value="Browse"/>
        </div>
        <div id="csv_progress_bar" data-bind="visible: csvInProgress"></div>
        <div id="csv_confirm_submit" data-bind="visible: csvToSendCertChain">
          <h2>Are You Sure?</h2>
          <br/>
          <p>You are about to create a new block containing <strong><span data-bind="text: csvTotalCertifications"></span> new certifications</strong>. Once the required parties have signed this block, it will be added to your institution's hashchain.</p>
          <p>If you wish to view the information that will be sent to the server before it leaves your device, <a href="">click here</a>.</p>
          <form method="post" action="{% url 'internal:queue_certifications' %}" data-bind="submit: csvSubmitForm">
            {% csrf_token %}
            <input type="hidden" name="certify_payload" data-bind="value: csvToSendCertChain"/>
            <button type="submit" class="cc-btn">CREATE NEW BLOCK</button>
            <button class="cc-btn" data-bind="click: csvCancelSubmission">CANCEL</button>
          </form>
        </div>
        <br/>
        <p style="text-align: center" data-bind="visible: csvToSendCertChain() == null"><b>To ensure data security, files you select here never leave your device unencrypted.</b><br/>All documents are encrypted on your device before transmission to the server.</p>
      </div>
    </div>
  </div>

  <br/><br/>

  <div class="row">
    <div class="span12">
      <h2>Certify Existing PDFs</h2>
      <p>Select one or more existing PDF files that you wish to certify.</p>
    </div>
  </div>
</div>
{% endblock content %}

www/internal/templates/internal/chain.html
{% extends "internal/auth_base.html" %}

{% load certchain_extras %}
{% load staticfiles %}

{% block stylesheets %}
  {{ block.super }}
  <link href="{% static 'internal/css/chain.css'%}" rel="stylesheet"/>
{% endblock stylesheets %}

{% block content %}
<div class="container cc-container">
  {% include "includes/menu.html" %}

  <div class="row">
    <div class="span7">
      <h2>Pending Blocks</h2>
      <p>The blocks below require an action from your institution or another before they can be added to your chain. Click on a block for specific details.</p>
      {% for block in pending_blocks %}
      {% if not block.system_generated %}
      <div class="block pending-block">
        <ul class="desc">
          <li>{{ block.description_for_admins }}</li>
          <li>Created {{ block.created_ts | cc_unix_ts_to_datetime }} by {{ block.created_by }}</li>
          <li>{{ block.num_certify_actions }} certifications, {{ block.num_revoke_actions }} revocations</li>
          <li>Signatures (__ of __ required): ___</li>
        </ul>
        <div class="actions">
          <div>SIGN</div>
          <div>
            <form method="post" action="{% url 'internal:discard_pending_block' %}">
              {% csrf_token %}
              <input name="discard_id" type="hidden" value="{{ block.id }}"/>
              <input class="cc-btn" type="submit" value="DISCARD"/>
            </form>
          </div>
          <div>
            <form method="post" action="{% url 'internal:submit_pending_block' %}">
              {% csrf_token %}
              <input name="submit_id" type="hidden" value="{{ block.id }}"/>
              <input class="cc-btn" type="submit" value="SUBMIT"/>
            </form>
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
    <div class="span5">
      <h2>Hashchain</h2>
      <p>The blocks below form your institution's hashchain. Click on an individual block for details.</p>
      {% if processing_block %}
      <div class="block processing-block">
        <ul class="desc">
          <li>{{ block.header.timestamp | cc_unix_ts_to_datetime }}</li>
        </ul>
        <div class="actions">
          <div>ABORT</div>
        </div>
      </div>
      {% endif %}
      {% for block in latest_n_hcblocks %}
      <div class="block hc-block">
        <ul class="desc">
          <li>Block <a href="{% url 'public:raw_block_by_hash' block.block_id %}">{{ block.block_id | slice:"0:25" }}...</a></li>
          <li>Created on {{ block.timestamp | cc_unix_ts_to_datetime }}</li>
          <li>Contains {{ block.num_certify_actions }} certifications, {{ block.num_revoke_actions }} revocations.</li>
          <li>Signed by {{ block.num_signoff_peers }} peers.</li>
          <li>Parent is {{ block.parent | slice:"0:25" }}...</li>
        </ul>
      </div>
      <img class="chain-arrow" src="{% static 'internal/images/chain_arrow.png' %}"/>
      {% endfor %}
      <center><button class="cc-btn">SHOW MORE BLOCKS</button></center>
    </div>
  </div>
</div>
{% endblock %}

www/internal/templates/internal/logged_out.html
{% extends "base.html" %}

{% block content %}
<div class="container cc-container">
  <div class="row">
    <div class="span12">
        <div id="cc-logout">
            <p>You have been succesfully logged out of CertChain.</p>
            <br/>
            <a class="cc-btn" href="/">RETURN TO LOGIN</a>
            </form>
        </div>
    </div>
  </div>
</div>
{% endblock %}

www/internal/templates/internal/login.html
{% extends "base.html" %}

{% block content %}
<div class="container cc-container">
  <div class="row">
    <div class="span12">
        <div id="cc-login">
            <p>Access to the administrative interface for
            this institution's CertChain node is restricted
            to authorized users. Please enter your credentials below.</p>

            {% if form.errors %}
            <p id="cc-login-error">Your username and password didn't match. Please try again.</p>
            {% endif %}

            {% if next %}
                {% if user.is_authenticated %}
                <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
                {% else %}
                <p>Please login to see this page.</p>
                {% endif %}
            {% endif %}

            <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
            {% csrf_token %}
            <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
            </table>

            <input class="cc-btn" type="submit" value="LOGIN" />
            <input type="hidden" name="next" value="{% url 'internal:overview' %}" />
            </form>
        </div>
    </div>
  </div>
</div>
{% endblock %}

www/internal/templates/internal/network.html
{% extends "internal/auth_base.html" %}

{% load certchain_extras %}
{% load staticfiles %}

{% block stylesheets %}
  {{ block.super }}
  <link href="{% static 'internal/css/overview.css'%}" rel="stylesheet"/>
{% endblock stylesheets %}

{% block content %}
<div class="container cc-container">
  {% include "includes/menu.html" %}

  <div class="row">
    <div class="span12">
      <h2>Your Network Presence</h2>
      <p>Other institutions connect to your institution using the information below. </p>
    </div>
  </div>

  <div class="netnode">
    <div class="row">
      <div class="span4">
        <span>{{ network.our_hostname }}</span>
        <label>Hostname</label>
      </div>
      <div class="span2">
        <span>{{ network.our_port }}</span>
        <label>Port</label>
      </div>
      <div class="span6">
        <span>{{ network.our_inst_addr }}</span>
        <label>Address</label>
      </div>
    </div>
  </div>

  <br/>
  <br/>

  <div class="row">
    <div class="span12">
      <h2>Add a Node</h2>
      <p>You will initiate and maintain connections with nodes that you enter here, and can optionally choose to peer with them after they are added to the list below.</p>
    </div>
  </div>

  <div class="row">
    <div class="span12">
      <div id="add-node">
        <form method="post" action="{% url 'internal:add_node' %}">
         {% csrf_token %}
          <div>
            <label>Hostname</label>
            <input name="hostname" type="text"/>
          </div>
          <div>
            <label>Port</label>
            <input name="port" type="text"/>
          </div>
          <div>
            <label>Address</label>
            <input name="address" type="text"/>
          </div>
          <input class="cc-btn" type="submit" value="ADD NODE"/>
        </form>
      </div>
    </div>
  </div>

  <br/>

  <div class="row">
    <div class="span12">
      <h2>Known Nodes</h2>
      <p>Your institution maintains contact with the institutions below.</p>
    </div>
  </div>

  {% for _, node in network.node_map.items %}
  <div class="netnode">
    <div class="row">
      <div class="span3">
        <span>{{ node.hostname }}</span>
        <label>Hostname</label>
      </div>
      <div class="span1">
        <span>{{ node.port }}</span>
        <label>Port</label>
      </div>
      <div class="span6">
        <span>{{ node.inst_addr }}</span>
        <label>Address</label>
      </div>
      <div class="span2">
        <form class="forget-node" method="post" action="{% url 'internal:remove_node' %}">
          {% csrf_token %}
          <input name="inst_addr" type="hidden" value="{{ node.inst_addr }}"/>
          <input class="cc-btn" type="submit" value="FORGET NODE"/>
        </form>
      </div>
    </div>
  </div>
  <div class="netnode-states">
    <table>
      <tr>
        {% if node.conn_state == 'Connected' %}
          {% if node.ident_state == 'Confirmed' %}
          <td><span class="state green">CONNECTION</span></td>
          <td>Your institution is connected to this node.</td>
          {% else %}
          <td><span class="state yellow">CONNECTION</span></td>
          <td>Your institution is connected to this node, but they have not proved their identity to you.</td>
          {% endif %}
        <td></td>
        {% else %}
        <td>
          <span class="state red">CONNECTION</span>
        </td>
        <td>
          Your institution is not connected to this node.
        </td>
        <td></td>
        {% endif %}
      </tr>
      <tr>
        {% if node.our_peering_approval == 'Approved' %}
        <td>
          <span class="state green">PEERING</span>
        </td>
        <td>
          You are peering with this institution.
        </td>
        <td>
          <form class="peering-form" method="post" action="{% url 'internal:end_peering' %}">
            {% csrf_token %}
            <input type="hidden" name="addr" value="{{node.inst_addr}}"/>
            <input class="cc-btn" type="submit" value="END PEERING"/>
          </form>
        </td>
        {% endif %}
        {% if node.our_peering_approval == 'NotApproved' %}
        <td>
          <span class="state gray">PEERING</span>
        </td>
        <td>
          You are not peering with this institution.
        </td>
        <td>
          <form class="peering-form" method="post" action="{% url 'internal:request_peer' %}">
            {% csrf_token %}
            <input type="hidden" name="addr" value="{{node.inst_addr}}"/>
            <input class="cc-btn" type="submit" value="REQUEST PEERING"/>
          </form>
        </td>
        {% endif %}
        {% if node.our_peering_approval == 'AwaitingTheirApproval' %}
        <td>
          <span class="state yellow">PEERING</span>
        </td>
        <td>
          This institution has not yet approved your peering request.
        </td>
        <td>
          <form class="peering-form" method="post" action="{% url 'internal:end_peering' %}">
            {% csrf_token %}
            <input type="hidden" name="addr" value="{{node.inst_addr}}"/>
            <input class="cc-btn" type="submit" value="CANCEL REQUEST"/>
          </form>
        </td>
        {% endif %}
        {% if node.our_peering_approval == 'AwaitingOurApproval' %}
        <td>
          <span class="state yellow">PEERING</span>
        </td>
        <td>
          This institution has requested a peering relationship with you.
        </td>
        <td></td>
        {% endif %}
      </tr>
    </table>
    {% if node.our_peering_approval == 'AwaitingOurApproval' %}
    <div class="peering-prompt">
      <span class="prompt">Do you approve of this institution's request to peer with you?</span>
      <br/>
      <span class="desc">If you approve, this institution's signature will be required on all of your future certifications and revocations, and vice versa.</span>
      <div class="options">
        <div class="left-half">
          <form method="post" action="{% url 'internal:approve_peer_request' %}">
            {% csrf_token %}
            <input type="hidden" name="requesting_addr" value="{{node.inst_addr}}"/>
            <input class="cc-btn green" type="submit" value="APPROVE"/>
          </form>
        </div>
        <div class="right-half">
          <form method="post" action="{% url 'internal:end_peering' %}">
            {% csrf_token %}
            <input type="hidden" name="addr" value="{{node.inst_addr}}"/>
            <input class="cc-btn red" type="submit" value="DENY"/>
          </form>
        </div>
      </div>
      <div style="clear: both"></div>
    </div>
    {% endif %}
  </div>
  {% empty %}
  <div class="row">
    <div class="span12">
      <p id="cc-no-institutions">Your institution is not in contact with any network nodes at this time.</p>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

www/internal/templates/internal/user_options.html
{% extends "internal/auth_base.html" %}

{% load certchain_extras %}
{% load staticfiles %}

{% block javascript %}
  <script type="text/javascript" src="{% static 'internal/js/jquery-1.10.2.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'public/js/forge.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'public/js/wrapper.js'%}"></script>
  <script type="text/javascript">
  $('document').ready(function(){
    secp256k1.init().then(function() {
        console.log('Loaded secp256k1.');
        var state = {};
        state.secret_key = new Uint8Array(64);
        window.crypto.getRandomValues(state.secret_key);
        console.log(state.secret_key)
        Promise.resolve().then(function(ret) {
          return secp256k1.api.point(state, {seckey: 'secret_key'});
        }).then(function(ret) {
          state.public_key = ret;
          console.log("Private key is: " + forge.util.bytesToHex(state.secret_key));
          console.log("Public key is: " + forge.util.bytesToHex(state.public_key));
        });
    });
  });
  </script>
{% endblock javascript %}

{% block content %}
<div class="container cc-container">
  {% include "includes/menu.html" %}

  <div class="row">
    <div class="span6">
      <h2>Your Signature Name</h2>
      <p>This is the name displayed to viewers of documents you have signed.</p>
    </div>
    <div class="span6">
      <label>Name</label>
      <input type="text" value="Matt Quinn"/>
    </div>
  </div>

  <br/>

  <div class="row">
    <div class="span6">
      <h2>Your Signing Keys</h2>
      <p>These are the keys you have created for use in signing off on changes to the hashchains you are authorized to administer.</p>
    </div>
    <div class="span6">
      <button class="cc-btn">CREATE NEW KEYPAIR</button>
    </div>
  </div>

{% endblock %}

www/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container cc-container">
  <div class="row">
    <div class="span6">
        <h1>Students, Faculty, Administrators</h1>
        <h2>Access your certified documents and create new ones; sign in here.</h2>
        <a href="{% url 'public:sso' %}"><button>WEBAUTH LOGIN</button></a>
        <hr/>
        <h1>Public Visitors</h1>
        <h2>You can download this institution's chain here. To access a specific document, use the authorized link provided to you by the document's owner.</h2>
        <button>DOWNLOAD CHAIN</button>
    </div>
    <div class="span6">
        <h1>Chain Status</h1>
        <h3>as of December 17th, 2016 13:11 EAT</h3>
    </div>
  </div>
</div>
{% endblock %}